[project]
name = "story-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.2.3",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]
